sudo: false

language: node_js
node_js:
  - 9

script: echo "Running tests against $(node -v)..."

before_install:
  - npm install react
  - npm install react-dom
  - npm install prop-types

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: react-scripts test --env=jsdom --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

branches:
  only:
    - master
