= FormManager Data Handling
:source-highlighter: pygments
:pygments-style: manni
:source-language: javascript
:icons: font
:table-stripes: even
:prewrap!:
:toc:
:toc-placement!:
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[.small]#Last update: {localdate}#

NOTE: THIS IS A WORK IN PROGRESS


toc::[]


== Data & Value Methods

FM _caches_ and _synchronizes_ two separate sets of data.
It is important to understand the difference when deciding which
API methods to use.

Methods containing the word "data" target the Data cache,
while those containing "value" target the Values cache.
However changes to either cache are immediately _synced_ to the other.
When you want to programatically set data in a form-field,
a Value method should be used.
If you need to update the _source_ data, use a Data method.

Any change to _either_ cache will immediately update the Data cache.
If a data transformation is required, it is done on the fly.

=== Form 'Data

The 'Data' cache starts as a _copy_ of the data originally supplied to FM,
if any was. This cache has the same structure and fieldnames as the source.
When any 'data getter' (eg: `getData()`) is called,
the data will be returned in the source structure, ready to be posted.

FM tracks the _original_ data, so knows precisely which data has
changed since the form was initialized.
This is useful if you want to do a PATCH update.

Data tracking also allows FM to know whether the form is 'clean' or 'dirty'.
If a user changes a value, then later changes it _back_ to the original value,
FM knows that this data value is _no longer_ 'changed'.


=== Field 'Values'

The 'Values' cache contains the values supplied to the form fields via props.
These values may be a different data-type of format than the source data,
to suit the requirements of each field-type.

*The Values cache is a single level deep.* There has no _nested keys_.
Nested structures from the 'Data' cache are flattened to become 'paths',
like `"user.profile.address.street"`.
These paths are the keys used in the Values object,
and are used as the *fieldnames* in the form...



== Form 'State'

FM can also store 'state' that isn't part of the 'form data'. It uses this
internally for flags like `isDirty`, but it can also be used to store, and
pass, any type of data you wish. This could be arrays to populate picklists,
logic-flags, event handler, etc. ANYTHING you need to pass-down to components
 can be added to FM state. The `categoryList` and `subcategoryList` keys shown
 above are examples of how

Using form-state can be done 2 ways:

1. Use the methods available for setting and getting form-state, primarily:

[source]
----
form.setState(name, value);  // SETTER
form.getState(name);         // GETTER
form.state(name);            // GETTER ALIAS
----

2. Add a field configuration and specify `isData: false`;
then this 'data field' is stored as form-state instead of with other form-data.
This syntax can be useful to hide the details of what's data and what's state:

[source]
----
form.setValue(name, value);  // SETTER
form.getValue(name);         // GETTER
form.value(name);            // GETTER ALIAS
----

Below is an example for **syncing category and subcategory lists**. It requires a simple onChange function and a little FM configuration. Two variations are shown to illustrate the 2 methods described above.

==== State Methods

State can be used with simple `getState()` and `setState()` methods.
These methods also accept 'paths' for nested valued, like `"metadata.feedback"`.

[source]
----
let selectedCategory = 1;

function handleCategoryChange(field, category, form) {
    if (category !== selectedCategory) {
        selectedCategory = category;
        const subcategories = sampleSubcategories[category] || [];

        // Set the correct subcategories list, or a blank list
        form.setState('subcategoryList', subcategories);

        // Always clear the subcategory value when category changes
        form.setValue('subcategory', '');
    }
}

const formConfig = {
    initialData: {
        category:        selectedCategory,
        subcategory:     ''
    },
    initialState: {
        categoryList:    sampleCategories,
        subcategoryList: sampleSubcategories[selectedCategory]
    },
    fields: {
        category: {
            onChange: handleCategoryChange
        }
    }
}
----

==== State Using Data-Abstraction

All 'fields' have a default config flag added like `{ isData: true }`.
If you specify `{ isData: false }` in any field's 'config, the value of that
field will be synchronized with form-state _instead of_ form-data.
These values can be automatically cleaned, converted and formatted
just like a normal field.
This is useful if you want to display fields that are not part of the
'form data'.

[source]
----
const formConfig = {
    initialState: {
        feedback: '',
        metadata: {
            like: false
        }
    }
    fields: {
        feedback: {
            isData:   false,
            cleaning: {
                trim: true,
                trimInner: true
            },
            validation: {
                required: true,
                minLength: 2
            }
        },
        'metadata.like': {
            isData:   false,
            dataType: 'number',  // 1/0
            valueType: 'boolean' // true/false
        }
    }
}
----
