import React from 'react'
import PropTypes from 'prop-types'

import Typography from '@material-ui/core/Typography'
import Button from '@material-ui/core/Button'
import TextField from '@material-ui/core/TextField'
import Checkbox from '@material-ui/core/Checkbox'
import FormControl from '@material-ui/core/FormControl'
import FormControlLabel from '@material-ui/core/FormControlLabel'
import FormHelperText from '@material-ui/core/FormHelperText'

import { formatDate } from '../formatters'

// THESE ARE JUST DEMO HELPERS - not needed in real form
const getFieldValue = ( field, form ) => {
	const dataType = (field.validation || {}).dataType || 'text'
	const value = form.value( field.name )

	if (dataType === 'date' && value) {
		return formatDate( value, 'date-input-field' )
	}
	else if (dataType === 'boolean') {
		// For boolean values, it is the 'checked' attribute this is used for
		if (typeof value === 'string') {
			return value === 'true'
		}
		else if (typeof value !== 'boolean') {
			return false
		}
	}

	return value
}

const getFieldName = field => field.aliasName || field.name

const getDisplayName = field =>
	field.displayName || field.aliasName || field.name

const getInputType = field => {
	switch ((field.validation || {}).dataType) {
		case 'date':
			return 'date'
		case 'boolean':
			return 'checkbox'
		default:
			return 'text'
	}
}


/**
 * Sample output of fields to validate form config
 */
class FieldsTestOutput extends React.Component {
	constructor( props ) {
		super( props )

		this.formAliasData = {}

		this.focusField = React.createRef()
	}

	componentDidMount() {
		// Auto-focus a field on-mount, if one passed in props
		const elem = this.focusField.current
		if (elem) elem.focus()
	}

	render() {
		const { props } = this
		const { form } = props
		const formFields = form.fieldConfig()

		// Transform hash to array for easy looping below
		// NOTE: Object.values() is not as supported as Object.keys()
		const arrFields = Object.keys( formFields ).map(
			fieldName => formFields[fieldName],
		)

		const style = {
			border: '1px solid #CCC',
			borderRadius: '4px',
			margin: '24px',
			padding: '16px',
		}

		return (
			<section style={style}>
				<Typography variant="title">
					Autogenerated Field Output
					<span className="field-required-mark"/>
				</Typography>

				<Typography variant="body1" className="form-tip">
					This tool can be used to verify data, field-configuration and
					validation options.
				</Typography>
				<hr/>

				{arrFields.map( field => {
					const aliasName = getFieldName( field )
					const displayName = getDisplayName( field )
					const inputType = getInputType( field )
					const ref = aliasName === props.focus ? this.focusField : null

					// NEVER set a value to Null or Undefined, because this
					// indicates the field is 'uncontrolled'
					this.formAliasData[aliasName] = getFieldValue( field, form )

					/* DEBUGGING
					 console.log(
					 `${displayName}:`,
					 `${/(text|date)/.test(inputType) ? '"' + value + '"' : value}`,
					 ` (${inputType})`
					 )
					 */

					if (inputType === 'checkbox') {
						return (
							<FormControl
								key={aliasName}
								fullWidth={true}
								margin="dense"
								error={form.hasErrors( aliasName )}
							>
								<FormControlLabel
									label={displayName}
									control={
										<Checkbox
											{...form.dataProps(
												aliasName,
												{ checkbox: true },
											)}
											color="primary"
											inputRef={ref}
										/>
									}
								/>
								<FormHelperText className="hide-when-empty">
									{form.errors( aliasName )}
								</FormHelperText>
							</FormControl>
						)
					}
					else {
						return (
							<TextField
								key={aliasName}
								label={displayName}
								{...form.dataProps( aliasName )}
								{...form.errorProps( aliasName )}
								fullWidth={true}
								margin="dense"
								inputRef={ref}
							/>
						)
					}
				} )}

				{props.submitForm && (
					<Typography variant="body1" className="form-tip">
						<Button color="primary" onClick={props.submitForm}>
							Save / Submit
						</Button>
					</Typography>
				)}
			</section>
		)
	}
}


const { func, string } = PropTypes

FieldsTestOutput.propTypes = {
	focus: string,
	submitForm: func,
}


export default FieldsTestOutput
